spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://test.cjudqgucury7.ap-southeast-1.rds.amazonaws.com:3306/ty_hrsrc?useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false&useSSL=false&connectTimeout=30000&socketTimeout=60000
    username: pIfGnW2B9V35f2J5mOwk0Q==
    password: QxHibVZiFCzTQ2S4IznwkBMPW/1NMQLateYrprbT7vo=
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1800000
      auto-commit: true
      validation-timeout: 5000
      connection-test-query: SELECT 1
  thymeleaf:
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  messages:
    basename: i18n.login
    encoding: UTF-8
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      location: ./uploads
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 20MB
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.pmp.hrsrc.entity
  logging:
    level:
      com.pmp.hrsrc.mapper: DEBUG
      java.sql: DEBUG
      org.mybatis.spring: DEBUG
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 900s  # 15分钟